package python

import (
	"bytes"
	"fmt"
	"github.com/snowmerak/antiserial/compiler/ast"
	"github.com/snowmerak/antiserial/compiler/codegen"
)

// Generate translates the AST into safe, high-performance Python source code.
func Generate(schemaAST ast.AST) (string, error) {
	var buf bytes.Buffer

	// File Header and imports
	buf.WriteString(`# Code generated by asc. DO NOT EDIT.
import struct
`)

	// Generate Python classes
	for _, s := range schemaAST.Structs {
		buf.WriteString(fmt.Sprintf("\nclass %s:\n", s.Name))

		// Constructor (__init__)
		buf.WriteString("    def __init__(self):\n")
		for _, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("        self.%s: %s = %s\n", field.Name, toPyType(field.Type), defaultPyValue(field.Type)))
		}
		if len(s.Fields) == 0 {
			buf.WriteString("        pass\n")
		}

		// Serialize Method
		buf.WriteString("\n    def serialize(self, buf: bytearray):\n")
		for i, field := range s.Fields {
			presenceExpr := genPresenceCheck("self."+field.Name, field.Type)
			buf.WriteString(fmt.Sprintf("        f%d_present = %s\n", i, presenceExpr))
		}

		numFields := len(s.Fields)
		numBitmapBytes := (numFields + 6) / 7
		if numBitmapBytes == 0 {
			numBitmapBytes = 1
		}

		// Write bitmap bytes
		for b := 0; b < numBitmapBytes; b++ {
			buf.WriteString(fmt.Sprintf("        b%d = 0\n", b))
			for bit := 0; bit < 7; bit++ {
				fieldIdx := b*7 + bit
				if fieldIdx < numFields {
					buf.WriteString(fmt.Sprintf("        if f%d_present:\n            b%d |= 1 << %d\n", fieldIdx, b, bit))
				}
			}
			if b < numBitmapBytes-1 {
				buf.WriteString(fmt.Sprintf("        b%d |= 1 << 7\n", b))
			}
			buf.WriteString(fmt.Sprintf("        buf.append(b%d)\n", b))
		}

		// Serialize present fields
		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("        if f%d_present:\n", i))
			serializeCode := genSerializeType(field.Type, "self."+field.Name, 0)
			buf.WriteString(indent(serializeCode, "            "))
			buf.WriteString("\n")
		}
		if len(s.Fields) == 0 {
			buf.WriteString("        pass\n")
		}

		// Deserialize Method
		buf.WriteString("\n    def deserialize(self, buf: bytes, offset: int) -> int:\n")
		buf.WriteString(`        bitmap_start = offset
        while True:
            if offset >= len(buf):
                raise ValueError("Unexpected EOF reading bitmap")
            b = buf[offset]
            offset += 1
            if (b & 0x80) == 0:
                break
        bitmap_bytes = buf[bitmap_start:offset]
        bitmap_len = len(bitmap_bytes)

        def is_present(field_idx: int) -> bool:
            byte_idx = field_idx // 7
            bit_idx = field_idx % 7
            if byte_idx >= bitmap_len:
                return False
            return (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0
`)

		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("\n        if is_present(%d):\n", i))
			deserializeCode := genDeserializeType(field.Type, "self."+field.Name, 0)
			buf.WriteString(indent(deserializeCode, "            "))
			buf.WriteString("\n")
		}
		buf.WriteString("        return offset\n")
	}

	return buf.String(), nil
}

// toPyType maps an AST type to a Python type annotation.
func toPyType(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "bool"
		case "int32", "uint32", "int64", "uint64":
			return "int"
		case "float32", "float", "float64", "double":
			return "float"
		case "string":
			return "str"
		case "bytes":
			return "bytes"
		default:
			return t.Name
		}
	case ast.TypeStruct:
		return fmt.Sprintf("'%s'", t.Name)
	case ast.TypeList:
		return fmt.Sprintf("list[%s]", toPyType(*t.ElemType))
	case ast.TypeMap:
		return fmt.Sprintf("dict[%s, %s]", toPyType(*t.KeyType), toPyType(*t.ValType))
	default:
		return "any"
	}
}

// defaultPyValue returns the default constructor value in Python.
func defaultPyValue(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "False"
		case "int32", "uint32", "int64", "uint64":
			return "0"
		case "float32", "float", "float64", "double":
			return "0.0"
		case "string":
			return `""`
		case "bytes":
			return "b''"
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s()", t.Name)
	case ast.TypeList:
		return "[]"
	case ast.TypeMap:
		return "{}"
	}
	return "None"
}

// genPresenceCheck checks if a field is present in Python.
func genPresenceCheck(expr string, t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return expr
		case "int32", "uint32", "int64", "uint64":
			return expr + " != 0"
		case "float32", "float", "float64", "double":
			return expr + " != 0.0"
		case "string":
			return expr + ` != ""`
		case "bytes":
			return "len(" + expr + ") > 0"
		}
	case ast.TypeStruct:
		return "True"
	case ast.TypeList, ast.TypeMap:
		return "len(" + expr + ") > 0"
	}
	return "False"
}

// genSerializeType recursively generates Python serialization code.
func genSerializeType(t ast.FieldType, expr string, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("buf.append(1 if %s else 0)", expr)
		case "int32":
			return fmt.Sprintf("buf.extend(struct.pack('<i', %s))", expr)
		case "uint32":
			return fmt.Sprintf("buf.extend(struct.pack('<I', %s))", expr)
		case "int64":
			return fmt.Sprintf("buf.extend(struct.pack('<q', %s))", expr)
		case "uint64":
			return fmt.Sprintf("buf.extend(struct.pack('<Q', %s))", expr)
		case "float32", "float":
			return fmt.Sprintf("buf.extend(struct.pack('<f', %s))", expr)
		case "float64", "double":
			return fmt.Sprintf("buf.extend(struct.pack('<d', %s))", expr)
		case "string":
			return fmt.Sprintf(`encoded = %s.encode('utf-8')
if len(encoded) > %d:
    raise ValueError(f"string length {len(encoded)} exceeds uint16 maximum %d")
buf.extend(len(encoded).to_bytes(2, 'little'))
buf.extend(encoded)`, expr, codegen.MaxUint16, codegen.MaxUint16)
		case "bytes":
			return fmt.Sprintf(`if len(%s) > 0xFFFFFFFF:
    raise ValueError(f"bytes length {len(%s)} exceeds uint32 maximum")
buf.extend(len(%s).to_bytes(4, 'little'))
buf.extend(%s)`, expr, expr, expr, expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s.serialize(buf)", expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemCode := genSerializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`count = len(%s)
if count > %d:
    raise ValueError(f"list length {count} exceeds uint16 maximum %d")
buf.extend(count.to_bytes(2, 'little'))
for %s in %s:
%s`, expr, codegen.MaxUint16, codegen.MaxUint16, elemName, expr, indent(elemCode, "    "))
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyCode := genSerializeType(*t.KeyType, keyName, depth+1)
		valCode := genSerializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`count = len(%s)
if count > %d:
    raise ValueError(f"map length {count} exceeds uint16 maximum %d")
buf.extend(count.to_bytes(2, 'little'))
for %s, %s in %s.items():
%s
%s`, expr, codegen.MaxUint16, codegen.MaxUint16, keyName, valName, expr, indent(keyCode, "    "), indent(valCode, "    "))
	}
	return ""
}

// genDeserializeType recursively generates Python deserialization code.
func genDeserializeType(t ast.FieldType, expr string, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf(`if offset >= len(buf):
    raise ValueError("Unexpected EOF")
%s = buf[offset] != 0
offset += 1`, expr)
		case "int32", "uint32", "int64", "uint64", "float32", "float", "float64", "double":
			size := t.PrimitiveFixedSize()
			fmtChar := ""
			switch t.Name {
			case "int32":
				fmtChar = "i"
			case "uint32":
				fmtChar = "I"
			case "int64":
				fmtChar = "q"
			case "uint64":
				fmtChar = "Q"
			case "float32", "float":
				fmtChar = "f"
			case "float64", "double":
				fmtChar = "d"
			}
			return fmt.Sprintf(`if offset + %d > len(buf):
    raise ValueError("Unexpected EOF")
%s = struct.unpack('<%s', buf[offset:offset+%d])[0]
offset += %d`, size, expr, fmtChar, size, size)
		case "string":
			return fmt.Sprintf(`if offset + 2 > len(buf):
    raise ValueError("Unexpected EOF")
length = int.from_bytes(buf[offset:offset+2], 'little')
offset += 2
if offset + length > len(buf):
    raise ValueError("Unexpected EOF")
%s = buf[offset:offset+length].decode('utf-8')
offset += length`, expr)
		case "bytes":
			return fmt.Sprintf(`if offset + 4 > len(buf):
    raise ValueError("Unexpected EOF")
length = int.from_bytes(buf[offset:offset+4], 'little')
offset += 4
if offset + length > len(buf):
    raise ValueError("Unexpected EOF")
%s = buf[offset:offset+length]
offset += length`, expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf(`offset = %s.deserialize(buf, offset)`, expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemTypeStr := t.ElemType.Name
		elemDefault := defaultPyValue(*t.ElemType)
		// Handle nested struct instantiation
		instantiation := ""
		if t.ElemType.Kind == ast.TypeStruct {
			instantiation = fmt.Sprintf("\n    %s = %s()", elemName, elemTypeStr)
		}
		elemCode := genDeserializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`if offset + 2 > len(buf):
    raise ValueError("Unexpected EOF")
count = int.from_bytes(buf[offset:offset+2], 'little')
offset += 2
%s = []
for _ in range(count):
    %s = %s%s
%s
    %s.append(%s)`, expr, elemName, elemDefault, instantiation, indent(elemCode, "    "), expr, elemName)
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyDefault := defaultPyValue(*t.KeyType)
		valDefault := defaultPyValue(*t.ValType)
		// Handle nested struct instantiation for values
		instantiationVal := ""
		if t.ValType.Kind == ast.TypeStruct {
			instantiationVal = fmt.Sprintf("\n    %s = %s()", valName, t.ValType.Name)
		}
		keyCode := genDeserializeType(*t.KeyType, keyName, depth+1)
		valCode := genDeserializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`if offset + 2 > len(buf):
    raise ValueError("Unexpected EOF")
count = int.from_bytes(buf[offset:offset+2], 'little')
offset += 2
%s = {}
for _ in range(count):
    %s = %s
%s
    %s = %s%s
%s
    %s[%s] = %s`, expr, keyName, keyDefault, indent(keyCode, "    "), valName, valDefault, instantiationVal, indent(valCode, "    "), expr, keyName, valName)
	}
	return ""
}

// indent prefixes each line of s with prefix.
func indent(s, prefix string) string {
	var buf bytes.Buffer
	lines := bytes.Split([]byte(s), []byte("\n"))
	for i, line := range lines {
		if i > 0 {
			buf.WriteByte('\n')
		}
		if len(line) > 0 {
			buf.WriteString(prefix)
			buf.Write(line)
		}
	}
	return buf.String()
}
