// Code generated by asc. DO NOT EDIT.
use std::convert::TryInto;

#[derive(Debug, Clone, PartialEq, Default)]
pub struct Geo {
    pub lat: f64,
    pub lng: f64,
}

impl Geo {
    pub fn serialize(&self, buf: &mut Vec<u8>) -> Result<(), &'static str> {
        let f0_present = self.lat != 0.0;
        let f1_present = self.lng != 0.0;
        let mut b0: u8 = 0;
        if f0_present {
            b0 |= 1 << 0;
        }
        if f1_present {
            b0 |= 1 << 1;
        }
        buf.push(b0);
        if f0_present {
            buf.extend_from_slice(&self.lat.to_le_bytes());
        }
        if f1_present {
            buf.extend_from_slice(&self.lng.to_le_bytes());
        }
        Ok(())
    }
    pub fn deserialize<'a>(buf: &'a [u8], offset: &mut usize) -> Result<Self, &'static str> {
        let bitmap_start = *offset;
        loop {
            if *offset >= buf.len() {
                return Err("Unexpected EOF reading bitmap");
            }
            let b = buf[*offset];
            *offset += 1;
            if (b & 0x80) == 0 {
                break;
            }
        }
        let bitmap_bytes = &buf[bitmap_start..*offset];

        let is_present = |field_idx: usize| -> bool {
            let byte_idx = field_idx / 7;
            let bit_idx = field_idx % 7;
            if byte_idx >= bitmap_bytes.len() {
                return false;
            }
            (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0
        };

        let mut s = Self::default();

        if is_present(0) {
            if *offset + 8 > buf.len() {
                return Err("Unexpected EOF");
            }
            s.lat = f64::from_le_bytes(buf[*offset..*offset+8].try_into().map_err(|_| "Slice convert error")?);
            *offset += 8;
        }

        if is_present(1) {
            if *offset + 8 > buf.len() {
                return Err("Unexpected EOF");
            }
            s.lng = f64::from_le_bytes(buf[*offset..*offset+8].try_into().map_err(|_| "Slice convert error")?);
            *offset += 8;
        }
        Ok(s)
    }
}

#[derive(Debug, Clone, PartialEq, Default)]
pub struct Payload<'a> {
    pub id: i64,
    pub uuid: &'a str,
    pub active: bool,
    pub tags: Vec<&'a str>,
}

impl<'a> Payload<'a> {
    pub fn serialize(&self, buf: &mut Vec<u8>) -> Result<(), &'static str> {
        let f0_present = self.id != 0;
        let f1_present = !self.uuid.is_empty();
        let f2_present = self.active;
        let f3_present = !self.tags.is_empty();
        let mut b0: u8 = 0;
        if f0_present {
            b0 |= 1 << 0;
        }
        if f1_present {
            b0 |= 1 << 1;
        }
        if f2_present {
            b0 |= 1 << 2;
        }
        if f3_present {
            b0 |= 1 << 3;
        }
        buf.push(b0);
        if f0_present {
            buf.extend_from_slice(&self.id.to_le_bytes());
        }
        if f1_present {
            {
                let bytes = self.uuid.as_bytes();
                if bytes.len() > 65535 {
                    return Err("string length exceeds uint16 maximum");
                }
                let length = bytes.len() as u16;
                buf.extend_from_slice(&length.to_le_bytes());
                buf.extend_from_slice(bytes);
            }
        }
        if f2_present {
            buf.push(if self.active { 1 } else { 0 });
        }
        if f3_present {
            {
                if self.tags.len() > 65535 {
                    return Err("list length exceeds uint16 maximum");
                }
                let count = self.tags.len() as u16;
                buf.extend_from_slice(&count.to_le_bytes());
                for elem0 in &self.tags {
                    {
                        let bytes = (*elem0).as_bytes();
                        if bytes.len() > 65535 {
                            return Err("string length exceeds uint16 maximum");
                        }
                        let length = bytes.len() as u16;
                        buf.extend_from_slice(&length.to_le_bytes());
                        buf.extend_from_slice(bytes);
                    }
                }
            }
        }
        Ok(())
    }
    pub fn deserialize(buf: &'a [u8], offset: &mut usize) -> Result<Self, &'static str> {
        let bitmap_start = *offset;
        loop {
            if *offset >= buf.len() {
                return Err("Unexpected EOF reading bitmap");
            }
            let b = buf[*offset];
            *offset += 1;
            if (b & 0x80) == 0 {
                break;
            }
        }
        let bitmap_bytes = &buf[bitmap_start..*offset];

        let is_present = |field_idx: usize| -> bool {
            let byte_idx = field_idx / 7;
            let bit_idx = field_idx % 7;
            if byte_idx >= bitmap_bytes.len() {
                return false;
            }
            (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0
        };

        let mut s = Self::default();

        if is_present(0) {
            if *offset + 8 > buf.len() {
                return Err("Unexpected EOF");
            }
            s.id = i64::from_le_bytes(buf[*offset..*offset+8].try_into().map_err(|_| "Slice convert error")?);
            *offset += 8;
        }

        if is_present(1) {
            if *offset + 2 > buf.len() {
                return Err("Unexpected EOF");
            }
            {
                let length = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
                *offset += 2;
                if *offset + length > buf.len() {
                    return Err("Unexpected EOF");
                }
                s.uuid = std::str::from_utf8(&buf[*offset..*offset+length]).map_err(|_| "Invalid UTF-8 sequence")?;
                *offset += length;
            }
        }

        if is_present(2) {
            if *offset >= buf.len() {
                return Err("Unexpected EOF");
            }
            s.active = buf[*offset] != 0;
            *offset += 1;
        }

        if is_present(3) {
            if *offset + 2 > buf.len() {
                return Err("Unexpected EOF");
            }
            {
                let count = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
                *offset += 2;
                let mut vec = Vec::with_capacity(count);
                for _ in 0..count {
                    let mut elem0 = "";
                    if *offset + 2 > buf.len() {
                        return Err("Unexpected EOF");
                    }
                    {
                        let length = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
                        *offset += 2;
                        if *offset + length > buf.len() {
                            return Err("Unexpected EOF");
                        }
                        elem0 = std::str::from_utf8(&buf[*offset..*offset+length]).map_err(|_| "Invalid UTF-8 sequence")?;
                        *offset += length;
                    }
                    vec.push(elem0);
                }
                s.tags = vec;
            }
        }
        Ok(s)
    }
}
