// Code generated by asc. DO NOT EDIT.

export const ANTISERIAL_MAX_UINT16 = 65535;

export class BufferWriter {
    private buf: Uint8Array;
    private view: DataView;
    private offset: number;

    constructor(initialCapacity = 1024) {
        this.buf = new Uint8Array(initialCapacity);
        this.view = new DataView(this.buf.buffer);
        this.offset = 0;
    }

    private ensureCapacity(size: number) {
        if (this.offset + size > this.buf.length) {
            const newBuf = new Uint8Array(Math.max(this.buf.length * 2, this.offset + size));
            newBuf.set(this.buf);
            this.buf = newBuf;
            this.view = new DataView(this.buf.buffer);
        }
    }

    writeUint8(val: number) {
        this.ensureCapacity(1);
        this.view.setUint8(this.offset, val);
        this.offset += 1;
    }

    writeUint16(val: number) {
        this.ensureCapacity(2);
        this.view.setUint16(this.offset, val, true);
        this.offset += 2;
    }

    writeUint32(val: number) {
        this.ensureCapacity(4);
        this.view.setUint32(this.offset, val, true);
        this.offset += 4;
    }

    writeUint64(val: bigint) {
        this.ensureCapacity(8);
        this.view.setBigUint64(this.offset, val, true);
        this.offset += 8;
    }

    writeInt32(val: number) {
        this.ensureCapacity(4);
        this.view.setInt32(this.offset, val, true);
        this.offset += 4;
    }

    writeInt64(val: bigint) {
        this.ensureCapacity(8);
        this.view.setBigInt64(this.offset, val, true);
        this.offset += 8;
    }

    writeFloat32(val: number) {
        this.ensureCapacity(4);
        this.view.setFloat32(this.offset, val, true);
        this.offset += 4;
    }

    writeFloat64(val: number) {
        this.ensureCapacity(8);
        this.view.setFloat64(this.offset, val, true);
        this.offset += 8;
    }

    writeString(val: string) {
        const encoder = new TextEncoder();
        const encoded = encoder.encode(val);
        if (encoded.length > ANTISERIAL_MAX_UINT16) {
            throw new Error("string length " + encoded.length + " exceeds uint16 maximum " + ANTISERIAL_MAX_UINT16);
        }
        this.writeUint16(encoded.length);
        this.ensureCapacity(encoded.length);
        this.buf.set(encoded, this.offset);
        this.offset += encoded.length;
    }

    writeBytes(val: Uint8Array) {
        if (val.length > 0xFFFFFFFF) {
            throw new Error("bytes length " + val.length + " exceeds uint32 maximum");
        }
        this.writeUint32(val.length);
        this.ensureCapacity(val.length);
        this.buf.set(val, this.offset);
        this.offset += val.length;
    }

    getFinishedBytes(): Uint8Array {
        return this.buf.subarray(0, this.offset);
    }
}

export class BufferReader {
    buf: Uint8Array;
    private view: DataView;
    offset: number;

    constructor(buf: Uint8Array, offset = 0) {
        this.buf = buf;
        this.view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        this.offset = offset;
    }

    readUint8(): number {
        if (this.offset + 1 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint8(this.offset);
        this.offset += 1;
        return val;
    }

    readUint16(): number {
        if (this.offset + 2 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint16(this.offset, true);
        this.offset += 2;
        return val;
    }

    readUint32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readUint64(): bigint {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getBigUint64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readInt32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getInt32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readInt64(): bigint {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getBigInt64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readFloat32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getFloat32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readFloat64(): number {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getFloat64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readString(): string {
        const len = this.readUint16();
        if (this.offset + len > this.buf.length) throw new Error("Unexpected EOF");
        const decoder = new TextDecoder("utf-8");
        const val = decoder.decode(this.buf.subarray(this.offset, this.offset + len));
        this.offset += len;
        return val;
    }

    readBytes(): Uint8Array {
        const len = this.readUint32();
        if (this.offset + len > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.buf.subarray(this.offset, this.offset + len);
        this.offset += len;
        return val;
    }
}

export class Geo {
    lat: number = 0;
    lng: number = 0;

    serialize(writer: BufferWriter) {
        const f0Present = this.lat !== 0;
        const f1Present = this.lng !== 0;
        let b0 = 0;
        if (f0Present) {
            b0 |= 1 << 0;
        }
        if (f1Present) {
            b0 |= 1 << 1;
        }
        writer.writeUint8(b0);
        if (f0Present) {
            writer.writeFloat64(this.lat);
        }
        if (f1Present) {
            writer.writeFloat64(this.lng);
        }
    }

    deserialize(reader: BufferReader) {
        const bitmapStart = reader.offset;
        let bitmapLen = 0;
        while (true) {
            const b = reader.readUint8();
            bitmapLen++;
            if ((b & 0x80) === 0) {
                break;
            }
        }
        const bitmapBytes = reader.buf.subarray(bitmapStart, bitmapStart + bitmapLen);

        const isPresent = (fieldIdx: number): boolean => {
            const byteIdx = Math.floor(fieldIdx / 7);
            const bitIdx = fieldIdx % 7;
            if (byteIdx >= bitmapBytes.length) {
                return false;
            }
            return (bitmapBytes[byteIdx] & (1 << bitIdx)) !== 0;
        };

        if (isPresent(0)) {
            this.lat = reader.readFloat64();
        }

        if (isPresent(1)) {
            this.lng = reader.readFloat64();
        }
    }
}

export class Payload {
    id: bigint = 0n;
    uuid: string = "";
    active: boolean = false;
    tags: string[] = [];

    serialize(writer: BufferWriter) {
        const f0Present = this.id !== 0n;
        const f1Present = this.uuid !== "";
        const f2Present = this.active;
        const f3Present = this.tags.length > 0;
        let b0 = 0;
        if (f0Present) {
            b0 |= 1 << 0;
        }
        if (f1Present) {
            b0 |= 1 << 1;
        }
        if (f2Present) {
            b0 |= 1 << 2;
        }
        if (f3Present) {
            b0 |= 1 << 3;
        }
        writer.writeUint8(b0);
        if (f0Present) {
            writer.writeInt64(this.id);
        }
        if (f1Present) {
            writer.writeString(this.uuid);
        }
        if (f2Present) {
            writer.writeUint8(this.active ? 1 : 0);
        }
        if (f3Present) {
            {
                const count = this.tags.length;
                if (count > ANTISERIAL_MAX_UINT16) {
                    throw new Error("list length " + count + " exceeds uint16 maximum " + ANTISERIAL_MAX_UINT16);
                }
                writer.writeUint16(count);
                for (const elem0 of this.tags) {
                    writer.writeString(elem0);
                }
            }
        }
    }

    deserialize(reader: BufferReader) {
        const bitmapStart = reader.offset;
        let bitmapLen = 0;
        while (true) {
            const b = reader.readUint8();
            bitmapLen++;
            if ((b & 0x80) === 0) {
                break;
            }
        }
        const bitmapBytes = reader.buf.subarray(bitmapStart, bitmapStart + bitmapLen);

        const isPresent = (fieldIdx: number): boolean => {
            const byteIdx = Math.floor(fieldIdx / 7);
            const bitIdx = fieldIdx % 7;
            if (byteIdx >= bitmapBytes.length) {
                return false;
            }
            return (bitmapBytes[byteIdx] & (1 << bitIdx)) !== 0;
        };

        if (isPresent(0)) {
            this.id = reader.readInt64();
        }

        if (isPresent(1)) {
            this.uuid = reader.readString();
        }

        if (isPresent(2)) {
            this.active = reader.readUint8() !== 0;
        }

        if (isPresent(3)) {
            {
                const count = reader.readUint16();
                this.tags = [];
                for (let i = 0; i < count; i++) {
                    let elem0: string = "";
                    elem0 = reader.readString();
                    this.tags.push(elem0);
                }
            }
        }
    }
}
