package rust

import (
	"bytes"
	"fmt"
	"github.com/snowmerak/antiserial/compiler/ast"
)

// Generate translates the AST into safe, high-performance, zero-copy Rust source code.
func Generate(schemaAST ast.AST) (string, error) {
	var buf bytes.Buffer

	// File Header
	buf.WriteString(`// Code generated by asc. DO NOT EDIT.
use std::convert::TryInto;
`)

	// Pre-calculate which structs require a lifetime 'a
	structLifetimes := make(map[string]bool)
	for _, s := range schemaAST.Structs {
		visited := make(map[string]bool)
		if hasStructLifetime(s.Name, schemaAST, visited) {
			structLifetimes[s.Name] = true
		}
	}


	// Generate Struct definitions and Serialize/Deserialize implementations
	for _, s := range schemaAST.Structs {
		lifetimeStr := ""
		if structLifetimes[s.Name] {
			lifetimeStr = "<'a>"
		}

		// Rust Struct Definition
		buf.WriteString(fmt.Sprintf("\n#[derive(Debug, Clone, PartialEq, Default)]\npub struct %s%s {\n", s.Name, lifetimeStr))
		for _, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("    pub %s: %s,\n", field.Name, toRustType(field.Type, structLifetimes)))
		}
		buf.WriteString("}\n")

		// Implement Serialize & Deserialize
		buf.WriteString(fmt.Sprintf("\nimpl%s %s%s {\n", lifetimeStr, s.Name, lifetimeStr))

		// Serialize Method
		buf.WriteString("    pub fn serialize(&self, buf: &mut Vec<u8>) {\n")
		// Check presence variables
		for i, field := range s.Fields {
			presenceExpr := genPresenceCheck("self."+field.Name, field.Type)
			buf.WriteString(fmt.Sprintf("        let f%d_present = %s;\n", i, presenceExpr))
		}

		numFields := len(s.Fields)
		numBitmapBytes := (numFields + 6) / 7
		if numBitmapBytes == 0 {
			numBitmapBytes = 1
		}

		// Initialize and write bitmap bytes
		for b := 0; b < numBitmapBytes; b++ {
			buf.WriteString(fmt.Sprintf("        let mut b%d: u8 = 0;\n", b))
			for bit := 0; bit < 7; bit++ {
				fieldIdx := b*7 + bit
				if fieldIdx < numFields {
					buf.WriteString(fmt.Sprintf("        if f%d_present {\n            b%d |= 1 << %d;\n        }\n", fieldIdx, b, bit))
				}
			}
			// Set continuation bit if there are more bitmap bytes
			if b < numBitmapBytes-1 {
				buf.WriteString(fmt.Sprintf("        b%d |= 1 << 7;\n", b))
			}
			buf.WriteString(fmt.Sprintf("        buf.push(b%d);\n", b))
		}

		// Serialize present fields
		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("        if f%d_present {\n", i))
			serializeCode := genSerializeType(field.Type, "self."+field.Name, 0)
			buf.WriteString(indent(serializeCode, "            "))
			buf.WriteString("\n        }\n")
		}
		buf.WriteString("    }\n")

		// Deserialize Method
		methodLifetime := ""
		if !structLifetimes[s.Name] {
			methodLifetime = "<'a>"
		}
		buf.WriteString(fmt.Sprintf("    pub fn deserialize%s(buf: &'a [u8], offset: &mut usize) -> Result<Self, &'static str> {\n", methodLifetime))
		buf.WriteString(`        let bitmap_start = *offset;
        loop {
            if *offset >= buf.len() {
                return Err("Unexpected EOF reading bitmap");
            }
            let b = buf[*offset];
            *offset += 1;
            if (b & 0x80) == 0 {
                break;
            }
        }
        let bitmap_bytes = &buf[bitmap_start..*offset];

        let is_present = |field_idx: usize| -> bool {
            let byte_idx = field_idx / 7;
            let bit_idx = field_idx % 7;
            if byte_idx >= bitmap_bytes.len() {
                return false;
            }
            (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0
        };

        let mut s = Self::default();
`)

		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("\n        if is_present(%d) {\n", i))
			deserializeCode := genDeserializeType(field.Type, "s."+field.Name, structLifetimes, 0)
			buf.WriteString(indent(deserializeCode, "            "))
			buf.WriteString("\n        }\n")
		}

		buf.WriteString("        Ok(s)\n    }\n}\n")
	}

	return buf.String(), nil
}

// hasStructLifetime transitively checks if a struct contains any lifetime-bound fields.
func hasStructLifetime(name string, schemaAST ast.AST, visited map[string]bool) bool {
	if visited[name] {
		return false
	}
	visited[name] = true

	s, ok := schemaAST.FindStruct(name)
	if !ok {
		return false
	}

	for _, f := range s.Fields {
		if hasLifetime(f.Type, schemaAST, visited) {
			return true
		}
	}
	return false
}

// hasLifetime checks if a type contains lifetime references.
func hasLifetime(t ast.FieldType, schemaAST ast.AST, visited map[string]bool) bool {
	switch t.Kind {
	case ast.TypePrimitive:
		return t.Name == "string" || t.Name == "bytes"
	case ast.TypeStruct:
		return hasStructLifetime(t.Name, schemaAST, visited)
	case ast.TypeList:
		return hasLifetime(*t.ElemType, schemaAST, visited)
	case ast.TypeMap:
		return hasLifetime(*t.KeyType, schemaAST, visited) || hasLifetime(*t.ValType, schemaAST, visited)
	}
	return false
}

// toRustType maps an AST type to a Rust type.
func toRustType(t ast.FieldType, structLifetimes map[string]bool) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "bool"
		case "int32":
			return "i32"
		case "uint32":
			return "u32"
		case "int64":
			return "i64"
		case "uint64":
			return "u64"
		case "float32", "float":
			return "f32"
		case "float64", "double":
			return "f64"
		case "string":
			return "&'a str"
		case "bytes":
			return "&'a [u8]"
		default:
			return t.Name
		}
	case ast.TypeStruct:
		lt := ""
		if structLifetimes[t.Name] {
			lt = "<'a>"
		}
		return t.Name + lt
	case ast.TypeList:
		return "Vec<" + toRustType(*t.ElemType, structLifetimes) + ">"
	case ast.TypeMap:
		return "std::collections::HashMap<" + toRustType(*t.KeyType, structLifetimes) + ", " + toRustType(*t.ValType, structLifetimes) + ">"
	default:
		return ""
	}
}

// genPresenceCheck checks if a field is present in Rust.
func genPresenceCheck(expr string, t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return expr
		case "int32", "uint32", "int64", "uint64":
			return expr + " != 0"
		case "float32", "float", "float64", "double":
			return expr + " != 0.0"
		case "string", "bytes":
			return "!" + expr + ".is_empty()"
		}
	case ast.TypeStruct:
		return "true"
	case ast.TypeList, ast.TypeMap:
		return "!" + expr + ".is_empty()"
	}
	return "false"
}

// genSerializeType recursively generates Rust serialization code.
func genSerializeType(t ast.FieldType, expr string, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("buf.push(if %s { 1 } else { 0 });", expr)
		case "int32", "uint32", "int64", "uint64", "float32", "float", "float64", "double":
			return fmt.Sprintf("buf.extend_from_slice(&%s.to_le_bytes());", expr)
		case "string":
			return fmt.Sprintf(`{
    let bytes = %s.as_bytes();
    let length = bytes.len() as u16;
    buf.extend_from_slice(&length.to_le_bytes());
    buf.extend_from_slice(bytes);
}`, expr)
		case "bytes":
			return fmt.Sprintf(`{
    let length = %s.len() as u32;
    buf.extend_from_slice(&length.to_le_bytes());
    buf.extend_from_slice(%s);
}`, expr, expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s.serialize(buf);", expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemCode := genSerializeType(*t.ElemType, "(*"+elemName+")", depth+1)
		return fmt.Sprintf(`{
    let count = %s.len() as u16;
    buf.extend_from_slice(&count.to_le_bytes());
    for %s in &%s {
%s
    }
}`, expr, elemName, expr, indent(elemCode, "        "))
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyCode := genSerializeType(*t.KeyType, "(*"+keyName+")", depth+1)
		valCode := genSerializeType(*t.ValType, "(*"+valName+")", depth+1)
		return fmt.Sprintf(`{
    let count = %s.len() as u16;
    buf.extend_from_slice(&count.to_le_bytes());
    for (%s, %s) in &%s {
%s
%s
    }
}`, expr, keyName, valName, expr, indent(keyCode, "        "), indent(valCode, "        "))
	}
	return ""
}

// genDeserializeType recursively generates Rust deserialization code.
func genDeserializeType(t ast.FieldType, expr string, structLifetimes map[string]bool, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf(`if *offset >= buf.len() {
    return Err("Unexpected EOF");
}
%s = buf[*offset] != 0;
*offset += 1;`, expr)
		case "int32", "uint32", "int64", "uint64", "float32", "float", "float64", "double":
			size := t.PrimitiveFixedSize()
			rustType := toRustType(t, structLifetimes)
			return fmt.Sprintf(`if *offset + %d > buf.len() {
    return Err("Unexpected EOF");
}
%s = %s::from_le_bytes(buf[*offset..*offset+%d].try_into().map_err(|_| "Slice convert error")?);
*offset += %d;`, size, expr, rustType, size, size)
		case "string":
			return fmt.Sprintf(`if *offset + 2 > buf.len() {
    return Err("Unexpected EOF");
}
{
    let length = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
    *offset += 2;
    if *offset + length > buf.len() {
        return Err("Unexpected EOF");
    }
    %s = std::str::from_utf8(&buf[*offset..*offset+length]).map_err(|_| "Invalid UTF-8 sequence")?;
    *offset += length;
}`, expr)
		case "bytes":
			return fmt.Sprintf(`if *offset + 4 > buf.len() {
    return Err("Unexpected EOF");
}
{
    let length = u32::from_le_bytes(buf[*offset..*offset+4].try_into().map_err(|_| "Slice convert error")?) as usize;
    *offset += 4;
    if *offset + length > buf.len() {
        return Err("Unexpected EOF");
    }
    %s = &buf[*offset..*offset+length];
    *offset += length;
}`, expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf(`%s = %s::deserialize(buf, offset)?;`, expr, t.Name)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemDefault := defaultRustValue(*t.ElemType, structLifetimes)
		elemCode := genDeserializeType(*t.ElemType, elemName, structLifetimes, depth+1)
		return fmt.Sprintf(`if *offset + 2 > buf.len() {
    return Err("Unexpected EOF");
}
{
    let count = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
    *offset += 2;
    let mut vec = Vec::with_capacity(count);
    for _ in 0..count {
        let mut %s = %s;
%s
        vec.push(%s);
    }
    %s = vec;
}`, elemName, elemDefault, indent(elemCode, "        "), elemName, expr)
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyDefault := defaultRustValue(*t.KeyType, structLifetimes)
		valDefault := defaultRustValue(*t.ValType, structLifetimes)
		keyCode := genDeserializeType(*t.KeyType, keyName, structLifetimes, depth+1)
		valCode := genDeserializeType(*t.ValType, valName, structLifetimes, depth+1)
		return fmt.Sprintf(`if *offset + 2 > buf.len() {
    return Err("Unexpected EOF");
}
{
    let count = u16::from_le_bytes(buf[*offset..*offset+2].try_into().map_err(|_| "Slice convert error")?) as usize;
    *offset += 2;
    let mut map = std::collections::HashMap::with_capacity(count);
    for _ in 0..count {
        let mut %s = %s;
%s
        let mut %s = %s;
%s
        map.insert(%s, %s);
    }
    %s = map;
}`, keyName, keyDefault, indent(keyCode, "        "), valName, valDefault, indent(valCode, "        "), keyName, valName, expr)
	}
	return ""
}

// defaultRustValue returns the default initializer expression for Rust variables.
func defaultRustValue(t ast.FieldType, structLifetimes map[string]bool) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "false"
		case "int32", "uint32", "int64", "uint64":
			return "0"
		case "float32", "float", "float64", "double":
			return "0.0"
		case "string":
			return `""`
		case "bytes":
			return "&[]"
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s::default()", t.Name)
	case ast.TypeList:
		return "Vec::new()"
	case ast.TypeMap:
		return "std::collections::HashMap::new()"
	}
	return "Default::default()"
}

// indent prefixes each line of s with prefix.
func indent(s, prefix string) string {
	var buf bytes.Buffer
	lines := bytes.Split([]byte(s), []byte("\n"))
	for i, line := range lines {
		if i > 0 {
			buf.WriteByte('\n')
		}
		if len(line) > 0 {
			buf.WriteString(prefix)
			buf.Write(line)
		}
	}
	return buf.String()
}
