// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: test/testgen_pb/payload.proto

package testgen_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_test_testgen_pb_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_test_testgen_pb_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_test_testgen_pb_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Payload) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Payload) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_test_testgen_pb_payload_proto protoreflect.FileDescriptor

const file_test_testgen_pb_payload_proto_rawDesc = "" +
	"\n" +
	"\x1dtest/testgen_pb/payload.proto\x12\n" +
	"testgen_pb\"Y\n" +
	"\aPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tagsB1Z/github.com/snowmerak/antiserial/test/testgen_pbb\x06proto3"

var (
	file_test_testgen_pb_payload_proto_rawDescOnce sync.Once
	file_test_testgen_pb_payload_proto_rawDescData []byte
)

func file_test_testgen_pb_payload_proto_rawDescGZIP() []byte {
	file_test_testgen_pb_payload_proto_rawDescOnce.Do(func() {
		file_test_testgen_pb_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_testgen_pb_payload_proto_rawDesc), len(file_test_testgen_pb_payload_proto_rawDesc)))
	})
	return file_test_testgen_pb_payload_proto_rawDescData
}

var file_test_testgen_pb_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_testgen_pb_payload_proto_goTypes = []any{
	(*Payload)(nil), // 0: testgen_pb.Payload
}
var file_test_testgen_pb_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_testgen_pb_payload_proto_init() }
func file_test_testgen_pb_payload_proto_init() {
	if File_test_testgen_pb_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_testgen_pb_payload_proto_rawDesc), len(file_test_testgen_pb_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_testgen_pb_payload_proto_goTypes,
		DependencyIndexes: file_test_testgen_pb_payload_proto_depIdxs,
		MessageInfos:      file_test_testgen_pb_payload_proto_msgTypes,
	}.Build()
	File_test_testgen_pb_payload_proto = out.File
	file_test_testgen_pb_payload_proto_goTypes = nil
	file_test_testgen_pb_payload_proto_depIdxs = nil
}
