package typescript

import (
	"bytes"
	"fmt"
	"github.com/snowmerak/antiserial/compiler/ast"
	"github.com/snowmerak/antiserial/compiler/codegen"
)

// Generate translates the AST into safe, high-performance TypeScript code.
func Generate(schemaAST ast.AST) (string, error) {
	var buf bytes.Buffer

	// File Header and helper BufferWriter/BufferReader classes
	buf.WriteString(fmt.Sprintf(`// Code generated by asc. DO NOT EDIT.

export const ANTISERIAL_MAX_UINT16 = %d;

`, codegen.MaxUint16))
	buf.WriteString(`export class BufferWriter {
    private buf: Uint8Array;
    private view: DataView;
    private offset: number;

    constructor(initialCapacity = 1024) {
        this.buf = new Uint8Array(initialCapacity);
        this.view = new DataView(this.buf.buffer);
        this.offset = 0;
    }

    private ensureCapacity(size: number) {
        if (this.offset + size > this.buf.length) {
            const newBuf = new Uint8Array(Math.max(this.buf.length * 2, this.offset + size));
            newBuf.set(this.buf);
            this.buf = newBuf;
            this.view = new DataView(this.buf.buffer);
        }
    }

    writeUint8(val: number) {
        this.ensureCapacity(1);
        this.view.setUint8(this.offset, val);
        this.offset += 1;
    }

    writeUint16(val: number) {
        this.ensureCapacity(2);
        this.view.setUint16(this.offset, val, true);
        this.offset += 2;
    }

    writeUint32(val: number) {
        this.ensureCapacity(4);
        this.view.setUint32(this.offset, val, true);
        this.offset += 4;
    }

    writeUint64(val: bigint) {
        this.ensureCapacity(8);
        this.view.setBigUint64(this.offset, val, true);
        this.offset += 8;
    }

    writeInt32(val: number) {
        this.ensureCapacity(4);
        this.view.setInt32(this.offset, val, true);
        this.offset += 4;
    }

    writeInt64(val: bigint) {
        this.ensureCapacity(8);
        this.view.setBigInt64(this.offset, val, true);
        this.offset += 8;
    }

    writeFloat32(val: number) {
        this.ensureCapacity(4);
        this.view.setFloat32(this.offset, val, true);
        this.offset += 4;
    }

    writeFloat64(val: number) {
        this.ensureCapacity(8);
        this.view.setFloat64(this.offset, val, true);
        this.offset += 8;
    }

    writeString(val: string) {
        const encoder = new TextEncoder();
        const encoded = encoder.encode(val);
        if (encoded.length > ANTISERIAL_MAX_UINT16) {
            throw new Error("string length " + encoded.length + " exceeds uint16 maximum " + ANTISERIAL_MAX_UINT16);
        }
        this.writeUint16(encoded.length);
        this.ensureCapacity(encoded.length);
        this.buf.set(encoded, this.offset);
        this.offset += encoded.length;
    }

    writeBytes(val: Uint8Array) {
        if (val.length > 0xFFFFFFFF) {
            throw new Error("bytes length " + val.length + " exceeds uint32 maximum");
        }
        this.writeUint32(val.length);
        this.ensureCapacity(val.length);
        this.buf.set(val, this.offset);
        this.offset += val.length;
    }

    getFinishedBytes(): Uint8Array {
        return this.buf.subarray(0, this.offset);
    }
}

export class BufferReader {
    buf: Uint8Array;
    private view: DataView;
    offset: number;

    constructor(buf: Uint8Array, offset = 0) {
        this.buf = buf;
        this.view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        this.offset = offset;
    }

    readUint8(): number {
        if (this.offset + 1 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint8(this.offset);
        this.offset += 1;
        return val;
    }

    readUint16(): number {
        if (this.offset + 2 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint16(this.offset, true);
        this.offset += 2;
        return val;
    }

    readUint32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getUint32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readUint64(): bigint {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getBigUint64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readInt32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getInt32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readInt64(): bigint {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getBigInt64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readFloat32(): number {
        if (this.offset + 4 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getFloat32(this.offset, true);
        this.offset += 4;
        return val;
    }

    readFloat64(): number {
        if (this.offset + 8 > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.view.getFloat64(this.offset, true);
        this.offset += 8;
        return val;
    }

    readString(): string {
        const len = this.readUint16();
        if (this.offset + len > this.buf.length) throw new Error("Unexpected EOF");
        const decoder = new TextDecoder("utf-8");
        const val = decoder.decode(this.buf.subarray(this.offset, this.offset + len));
        this.offset += len;
        return val;
    }

    readBytes(): Uint8Array {
        const len = this.readUint32();
        if (this.offset + len > this.buf.length) throw new Error("Unexpected EOF");
        const val = this.buf.subarray(this.offset, this.offset + len);
        this.offset += len;
        return val;
    }
}
`)

	// Generate TypeScript classes
	for _, s := range schemaAST.Structs {
		buf.WriteString(fmt.Sprintf("\nexport class %s {\n", s.Name))
		for _, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("    %s: %s = %s;\n", field.Name, toTsType(field.Type), defaultTsValue(field.Type)))
		}

		// Serialize Method
		buf.WriteString("\n    serialize(writer: BufferWriter) {\n")
		for i, field := range s.Fields {
			presenceExpr := genPresenceCheck("this."+field.Name, field.Type)
			buf.WriteString(fmt.Sprintf("        const f%dPresent = %s;\n", i, presenceExpr))
		}

		numFields := len(s.Fields)
		numBitmapBytes := (numFields + 6) / 7
		if numBitmapBytes == 0 {
			numBitmapBytes = 1
		}

		// Write bitmap bytes
		for b := 0; b < numBitmapBytes; b++ {
			buf.WriteString(fmt.Sprintf("        let b%d = 0;\n", b))
			for bit := 0; bit < 7; bit++ {
				fieldIdx := b*7 + bit
				if fieldIdx < numFields {
					buf.WriteString(fmt.Sprintf("        if (f%dPresent) {\n            b%d |= 1 << %d;\n        }\n", fieldIdx, b, bit))
				}
			}
			if b < numBitmapBytes-1 {
				buf.WriteString(fmt.Sprintf("        b%d |= 1 << 7;\n", b))
			}
			buf.WriteString(fmt.Sprintf("        writer.writeUint8(b%d);\n", b))
		}

		// Serialize present fields
		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("        if (f%dPresent) {\n", i))
			serializeCode := genSerializeType(field.Type, "this."+field.Name, 0)
			buf.WriteString(indent(serializeCode, "            "))
			buf.WriteString("\n        }\n")
		}
		buf.WriteString("    }\n")

		// Deserialize Method
		buf.WriteString("\n    deserialize(reader: BufferReader) {\n")
		buf.WriteString(`        const bitmapStart = reader.offset;
        let bitmapLen = 0;
        while (true) {
            const b = reader.readUint8();
            bitmapLen++;
            if ((b & 0x80) === 0) {
                break;
            }
        }
        const bitmapBytes = reader.buf.subarray(bitmapStart, bitmapStart + bitmapLen);

        const isPresent = (fieldIdx: number): boolean => {
            const byteIdx = Math.floor(fieldIdx / 7);
            const bitIdx = fieldIdx % 7;
            if (byteIdx >= bitmapBytes.length) {
                return false;
            }
            return (bitmapBytes[byteIdx] & (1 << bitIdx)) !== 0;
        };
`)

		for i, field := range s.Fields {
			buf.WriteString(fmt.Sprintf("\n        if (isPresent(%d)) {\n", i))
			deserializeCode := genDeserializeType(field.Type, "this."+field.Name, 0)
			buf.WriteString(indent(deserializeCode, "            "))
			buf.WriteString("\n        }\n")
		}
		buf.WriteString("    }\n}\n")
	}

	return buf.String(), nil
}

// toTsType maps an AST type to a TypeScript type.
func toTsType(t ast.FieldType) string {
	base := toTsTypeValue(t)
	if t.Optional {
		return base + " | null"
	}
	return base
}

func toTsTypeValue(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "boolean"
		case "int32", "uint32", "float32", "float", "float64", "double":
			return "number"
		case "int64", "uint64":
			return "bigint"
		case "string":
			return "string"
		case "bytes":
			return "Uint8Array"
		default:
			return t.Name
		}
	case ast.TypeStruct:
		return t.Name
	case ast.TypeList:
		return toTsTypeValue(*t.ElemType) + "[]"
	case ast.TypeMap:
		return "Map<" + toTsTypeValue(*t.KeyType) + ", " + toTsTypeValue(*t.ValType) + ">"
	default:
		return ""
	}
}

// defaultTsValue returns the default initializer string for a TS field.
func defaultTsValue(t ast.FieldType) string {
	if t.Optional {
		return "null"
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "false"
		case "int32", "uint32", "float32", "float", "float64", "double":
			return "0"
		case "int64", "uint64":
			return "0n"
		case "string":
			return `""`
		case "bytes":
			return "new Uint8Array(0)"
		}
	case ast.TypeStruct:
		return fmt.Sprintf("new %s()", t.Name)
	case ast.TypeList:
		return "[]"
	case ast.TypeMap:
		return "new Map()"
	}
	return "null"
}

// genPresenceCheck checks if a field is present in TS.
func genPresenceCheck(expr string, t ast.FieldType) string {
	if t.Optional {
		return expr + " !== null"
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return expr
		case "int32", "uint32", "float32", "float", "float64", "double":
			return expr + " !== 0"
		case "int64", "uint64":
			return expr + " !== 0n"
		case "string":
			return expr + ` !== ""`
		case "bytes":
			return expr + ".length > 0"
		}
	case ast.TypeStruct:
		return "true"
	case ast.TypeList:
		return expr + ".length > 0"
	case ast.TypeMap:
		return expr + ".size > 0"
	}
	return "false"
}

// genSerializeType recursively generates TypeScript serialization code.
func genSerializeType(t ast.FieldType, expr string, depth int) string {
	if t.Optional {
		inner := t
		inner.Optional = false
		body := genSerializeType(inner, "v", depth)
		return fmt.Sprintf("if (%s !== null) {\n        const v = %s!;\n%s\n    }", expr, expr, indent(body, "        "))
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("writer.writeUint8(%s ? 1 : 0);", expr)
		case "int32":
			return fmt.Sprintf("writer.writeInt32(%s);", expr)
		case "uint32":
			return fmt.Sprintf("writer.writeUint32(%s);", expr)
		case "int64":
			return fmt.Sprintf("writer.writeInt64(%s);", expr)
		case "uint64":
			return fmt.Sprintf("writer.writeUint64(%s);", expr)
		case "float32", "float":
			return fmt.Sprintf("writer.writeFloat32(%s);", expr)
		case "float64", "double":
			return fmt.Sprintf("writer.writeFloat64(%s);", expr)
		case "string":
			return fmt.Sprintf("writer.writeString(%s);", expr)
		case "bytes":
			return fmt.Sprintf("writer.writeBytes(%s);", expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s.serialize(writer);", expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemCode := genSerializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`{
    const count = %s.length;
    if (count > ANTISERIAL_MAX_UINT16) {
        throw new Error("list length " + count + " exceeds uint16 maximum " + ANTISERIAL_MAX_UINT16);
    }
    writer.writeUint16(count);
    for (const %s of %s) {
%s
    }
}`, expr, elemName, expr, indent(elemCode, "        "))
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyCode := genSerializeType(*t.KeyType, keyName, depth+1)
		valCode := genSerializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`{
    const count = %s.size;
    if (count > ANTISERIAL_MAX_UINT16) {
        throw new Error("map length " + count + " exceeds uint16 maximum " + ANTISERIAL_MAX_UINT16);
    }
    writer.writeUint16(count);
    for (const [%s, %s] of %s) {
%s
%s
    }
}`, expr, keyName, valName, expr, indent(keyCode, "        "), indent(valCode, "        "))
	}
	return ""
}

// genDeserializeType recursively generates TypeScript deserialization code.
func genDeserializeType(t ast.FieldType, expr string, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("%s = reader.readUint8() !== 0;", expr)
		case "int32":
			return fmt.Sprintf("%s = reader.readInt32();", expr)
		case "uint32":
			return fmt.Sprintf("%s = reader.readUint32();", expr)
		case "int64":
			return fmt.Sprintf("%s = reader.readInt64();", expr)
		case "uint64":
			return fmt.Sprintf("%s = reader.readUint64();", expr)
		case "float32", "float":
			return fmt.Sprintf("%s = reader.readFloat32();", expr)
		case "float64", "double":
			return fmt.Sprintf("%s = reader.readFloat64();", expr)
		case "string":
			return fmt.Sprintf("%s = reader.readString();", expr)
		case "bytes":
			return fmt.Sprintf("%s = reader.readBytes();", expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf("%s.deserialize(reader);", expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemTypeStr := toTsType(*t.ElemType)
		elemCode := genDeserializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`{
    const count = reader.readUint16();
    %s = [];
    for (let i = 0; i < count; i++) {
        let %s: %s = %s;
%s
        %s.push(%s);
    }
}`, expr, elemName, elemTypeStr, defaultTsValue(*t.ElemType), indent(elemCode, "        "), expr, elemName)
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyTypeStr := toTsType(*t.KeyType)
		valTypeStr := toTsType(*t.ValType)
		keyCode := genDeserializeType(*t.KeyType, keyName, depth+1)
		valCode := genDeserializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`{
    const count = reader.readUint16();
    %s.clear();
    for (let i = 0; i < count; i++) {
        let %s: %s = %s;
%s
        let %s: %s = %s;
%s
        %s.set(%s, %s);
    }
}`, expr, keyName, keyTypeStr, defaultTsValue(*t.KeyType), indent(keyCode, "        "), valName, valTypeStr, defaultTsValue(*t.ValType), indent(valCode, "        "), expr, keyName, valName)
	}
	return ""
}

// indent prefixes each line of s with prefix.
func indent(s, prefix string) string {
	var buf bytes.Buffer
	lines := bytes.Split([]byte(s), []byte("\n"))
	for i, line := range lines {
		if i > 0 {
			buf.WriteByte('\n')
		}
		if len(line) > 0 {
			buf.WriteString(prefix)
			buf.Write(line)
		}
	}
	return buf.String()
}
