// Code generated by asc. DO NOT EDIT.
package testgen_v2

import (
	"io"
	"math"
	"unsafe"
)

type Geo struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

func (s *Geo) Marshal(buf []byte) []byte {
	f0Present := s.Lat != 0
	f1Present := s.Lng != 0
	var b0 byte
	if f0Present {
		b0 |= 1 << 0
	}
	if f1Present {
		b0 |= 1 << 1
	}
	buf = append(buf, b0)
	if f0Present {
		{
			v := math.Float64bits(s.Lat)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	if f1Present {
		{
			v := math.Float64bits(s.Lng)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	return buf
}

func (s *Geo) Unmarshal(buf []byte) (int, error) {
	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}

	if isPresent(0) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Lat = math.Float64frombits(v)
		}
		offset += 8
	}

	if isPresent(1) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Lng = math.Float64frombits(v)
		}
		offset += 8
	}
	return offset, nil
}

type Payload struct {
	Id     int64    `json:"id"`
	Uuid   string   `json:"uuid"`
	Active bool     `json:"active"`
	Tags   []string `json:"tags"`
}

func (s *Payload) Marshal(buf []byte) []byte {
	f0Present := s.Id != 0
	f1Present := s.Uuid != ""
	f2Present := s.Active
	f3Present := len(s.Tags) > 0
	var b0 byte
	if f0Present {
		b0 |= 1 << 0
	}
	if f1Present {
		b0 |= 1 << 1
	}
	if f2Present {
		b0 |= 1 << 2
	}
	if f3Present {
		b0 |= 1 << 3
	}
	buf = append(buf, b0)
	if f0Present {
		{
			v := uint64(s.Id)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	if f1Present {
		{
			length := len(s.Uuid)
			buf = append(buf, byte(length), byte(length>>8))
			buf = append(buf, s.Uuid...)
		}
	}
	if f2Present {
		if s.Active {
			buf = append(buf, 1)
		} else {
			buf = append(buf, 0)
		}
	}
	if f3Present {
		{
			count := len(s.Tags)
			buf = append(buf, byte(count), byte(count>>8))
			for _, elem0 := range s.Tags {
				{
					length := len(elem0)
					buf = append(buf, byte(length), byte(length>>8))
					buf = append(buf, elem0...)
				}
			}
		}
	}
	return buf
}

func (s *Payload) Unmarshal(buf []byte) (int, error) {
	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}

	if isPresent(0) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Id = int64(v)
		}
		offset += 8
	}

	if isPresent(1) {
		if offset+2 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			length := uint16(buf[offset]) | uint16(buf[offset+1])<<8
			offset += 2
			if offset+int(length) > len(buf) {
				return 0, io.ErrUnexpectedEOF
			}
			if length > 0 {
				s.Uuid = unsafe.String(&buf[offset], length)
				offset += int(length)
			} else {
				s.Uuid = ""
			}
		}
	}

	if isPresent(2) {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		s.Active = buf[offset] != 0
		offset++
	}

	if isPresent(3) {
		if offset+2 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			count := uint16(buf[offset]) | uint16(buf[offset+1])<<8
			offset += 2
			s.Tags = make([]string, count)
			for i := 0; i < int(count); i++ {
				var elem0 string
				if offset+2 > len(buf) {
					return 0, io.ErrUnexpectedEOF
				}
				{
					length := uint16(buf[offset]) | uint16(buf[offset+1])<<8
					offset += 2
					if offset+int(length) > len(buf) {
						return 0, io.ErrUnexpectedEOF
					}
					if length > 0 {
						elem0 = unsafe.String(&buf[offset], length)
						offset += int(length)
					} else {
						elem0 = ""
					}
				}
				s.Tags[i] = elem0
			}
		}
	}
	return offset, nil
}
