// Code generated by asc. DO NOT EDIT.
package testgen_nested

import (
	"io"
	"math"
)

type Geo struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

func (s *Geo) Marshal(buf []byte) ([]byte, error) {
	f0Present := s.Lat != 0
	f1Present := s.Lng != 0
	var b0 byte
	if f0Present {
		b0 |= 1 << 0
	}
	if f1Present {
		b0 |= 1 << 1
	}
	buf = append(buf, b0)
	if f0Present {
		{
			v := math.Float64bits(s.Lat)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	if f1Present {
		{
			v := math.Float64bits(s.Lng)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	return buf, nil
}

func (s *Geo) Unmarshal(buf []byte) (int, error) {
	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}

	if isPresent(0) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Lat = math.Float64frombits(v)
		}
		offset += 8
	}

	if isPresent(1) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Lng = math.Float64frombits(v)
		}
		offset += 8
	}
	return offset, nil
}

type WithGeo struct {
	Id  int64 `json:"id"`
	Geo Geo   `json:"geo"`
}

func (s *WithGeo) Marshal(buf []byte) ([]byte, error) {
	f0Present := s.Id != 0
	f1Present := true
	var b0 byte
	if f0Present {
		b0 |= 1 << 0
	}
	if f1Present {
		b0 |= 1 << 1
	}
	buf = append(buf, b0)
	if f0Present {
		{
			v := uint64(s.Id)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	if f1Present {
		{
			var err error
			buf, err = s.Geo.Marshal(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *WithGeo) Unmarshal(buf []byte) (int, error) {
	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}

	if isPresent(0) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Id = int64(v)
		}
		offset += 8
	}

	if isPresent(1) {
		{
			n, err := (&s.Geo).Unmarshal(buf[offset:])
			if err != nil {
				return 0, err
			}
			offset += n
		}
	}
	return offset, nil
}
