# Code generated by asc. DO NOT EDIT.
import struct

class Geo:
    def __init__(self):
        self.lat: float = 0.0
        self.lng: float = 0.0

    def serialize(self, buf: bytearray):
        f0_present = self.lat != 0.0
        f1_present = self.lng != 0.0
        b0 = 0
        if f0_present:
            b0 |= 1 << 0
        if f1_present:
            b0 |= 1 << 1
        buf.append(b0)
        if f0_present:
            buf.extend(struct.pack('<d', self.lat))
        if f1_present:
            buf.extend(struct.pack('<d', self.lng))

    def deserialize(self, buf: bytes, offset: int) -> int:
        bitmap_start = offset
        while True:
            if offset >= len(buf):
                raise ValueError("Unexpected EOF reading bitmap")
            b = buf[offset]
            offset += 1
            if (b & 0x80) == 0:
                break
        bitmap_bytes = buf[bitmap_start:offset]
        bitmap_len = len(bitmap_bytes)

        def is_present(field_idx: int) -> bool:
            byte_idx = field_idx // 7
            bit_idx = field_idx % 7
            if byte_idx >= bitmap_len:
                return False
            return (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0

        if is_present(0):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.lat = struct.unpack('<d', buf[offset:offset+8])[0]
            offset += 8

        if is_present(1):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.lng = struct.unpack('<d', buf[offset:offset+8])[0]
            offset += 8
        return offset

class WithGeo:
    def __init__(self):
        self.id: int = 0
        self.geo: 'Geo' = Geo()

    def serialize(self, buf: bytearray):
        f0_present = self.id != 0
        f1_present = True
        b0 = 0
        if f0_present:
            b0 |= 1 << 0
        if f1_present:
            b0 |= 1 << 1
        buf.append(b0)
        if f0_present:
            buf.extend(struct.pack('<q', self.id))
        if f1_present:
            self.geo.serialize(buf)

    def deserialize(self, buf: bytes, offset: int) -> int:
        bitmap_start = offset
        while True:
            if offset >= len(buf):
                raise ValueError("Unexpected EOF reading bitmap")
            b = buf[offset]
            offset += 1
            if (b & 0x80) == 0:
                break
        bitmap_bytes = buf[bitmap_start:offset]
        bitmap_len = len(bitmap_bytes)

        def is_present(field_idx: int) -> bool:
            byte_idx = field_idx // 7
            bit_idx = field_idx % 7
            if byte_idx >= bitmap_len:
                return False
            return (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0

        if is_present(0):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.id = struct.unpack('<q', buf[offset:offset+8])[0]
            offset += 8

        if is_present(1):
            offset = self.geo.deserialize(buf, offset)
        return offset
