# Code generated by asc. DO NOT EDIT.
import struct

class Geo:
    def __init__(self):
        self.lat: float = 0.0
        self.lng: float = 0.0

    def serialize(self, buf: bytearray):
        f0_present = self.lat != 0.0
        f1_present = self.lng != 0.0
        b0 = 0
        if f0_present:
            b0 |= 1 << 0
        if f1_present:
            b0 |= 1 << 1
        buf.append(b0)
        if f0_present:
            buf.extend(struct.pack('<d', self.lat))
        if f1_present:
            buf.extend(struct.pack('<d', self.lng))

    def deserialize(self, buf: bytes, offset: int) -> int:
        bitmap_start = offset
        while True:
            if offset >= len(buf):
                raise ValueError("Unexpected EOF reading bitmap")
            b = buf[offset]
            offset += 1
            if (b & 0x80) == 0:
                break
        bitmap_bytes = buf[bitmap_start:offset]
        bitmap_len = len(bitmap_bytes)

        def is_present(field_idx: int) -> bool:
            byte_idx = field_idx // 7
            bit_idx = field_idx % 7
            if byte_idx >= bitmap_len:
                return False
            return (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0

        if is_present(0):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.lat = struct.unpack('<d', buf[offset:offset+8])[0]
            offset += 8

        if is_present(1):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.lng = struct.unpack('<d', buf[offset:offset+8])[0]
            offset += 8
        return offset

class Payload:
    def __init__(self):
        self.id: int = 0
        self.uuid: str = ""
        self.active: bool = False
        self.tags: list[str] = []

    def serialize(self, buf: bytearray):
        f0_present = self.id != 0
        f1_present = self.uuid != ""
        f2_present = self.active
        f3_present = len(self.tags) > 0
        b0 = 0
        if f0_present:
            b0 |= 1 << 0
        if f1_present:
            b0 |= 1 << 1
        if f2_present:
            b0 |= 1 << 2
        if f3_present:
            b0 |= 1 << 3
        buf.append(b0)
        if f0_present:
            buf.extend(struct.pack('<q', self.id))
        if f1_present:
            encoded = self.uuid.encode('utf-8')
            buf.extend(len(encoded).to_bytes(2, 'little'))
            buf.extend(encoded)
        if f2_present:
            buf.append(1 if self.active else 0)
        if f3_present:
            count = len(self.tags)
            buf.extend(count.to_bytes(2, 'little'))
            for elem0 in self.tags:
                encoded = elem0.encode('utf-8')
                buf.extend(len(encoded).to_bytes(2, 'little'))
                buf.extend(encoded)

    def deserialize(self, buf: bytes, offset: int) -> int:
        bitmap_start = offset
        while True:
            if offset >= len(buf):
                raise ValueError("Unexpected EOF reading bitmap")
            b = buf[offset]
            offset += 1
            if (b & 0x80) == 0:
                break
        bitmap_bytes = buf[bitmap_start:offset]
        bitmap_len = len(bitmap_bytes)

        def is_present(field_idx: int) -> bool:
            byte_idx = field_idx // 7
            bit_idx = field_idx % 7
            if byte_idx >= bitmap_len:
                return False
            return (bitmap_bytes[byte_idx] & (1 << bit_idx)) != 0

        if is_present(0):
            if offset + 8 > len(buf):
                raise ValueError("Unexpected EOF")
            self.id = struct.unpack('<q', buf[offset:offset+8])[0]
            offset += 8

        if is_present(1):
            if offset + 2 > len(buf):
                raise ValueError("Unexpected EOF")
            length = int.from_bytes(buf[offset:offset+2], 'little')
            offset += 2
            if offset + length > len(buf):
                raise ValueError("Unexpected EOF")
            self.uuid = buf[offset:offset+length].decode('utf-8')
            offset += length

        if is_present(2):
            if offset >= len(buf):
                raise ValueError("Unexpected EOF")
            self.active = buf[offset] != 0
            offset += 1

        if is_present(3):
            if offset + 2 > len(buf):
                raise ValueError("Unexpected EOF")
            count = int.from_bytes(buf[offset:offset+2], 'little')
            offset += 2
            self.tags = []
            for _ in range(count):
                elem0 = ""
                if offset + 2 > len(buf):
                    raise ValueError("Unexpected EOF")
                length = int.from_bytes(buf[offset:offset+2], 'little')
                offset += 2
                if offset + length > len(buf):
                    raise ValueError("Unexpected EOF")
                elem0 = buf[offset:offset+length].decode('utf-8')
                offset += length
                self.tags.append(elem0)
        return offset
