// Code generated by asc. DO NOT EDIT.
package testgen_optional

import (
	"io"
)

type Payload struct {
	Id    int64  `json:"id"`
	Score *int32 `json:"score"`
}

func (s *Payload) Marshal(buf []byte) ([]byte, error) {
	f0Present := s.Id != 0
	f1Present := s.Score != nil
	var b0 byte
	if f0Present {
		b0 |= 1 << 0
	}
	if f1Present {
		b0 |= 1 << 1
	}
	buf = append(buf, b0)
	if f0Present {
		{
			v := uint64(s.Id)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
		}
	}
	if f1Present {
		{
			v := uint32(*s.Score)
			buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
		}
	}
	return buf, nil
}

func (s *Payload) Unmarshal(buf []byte) (int, error) {
	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}

	if isPresent(0) {
		if offset+8 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
			s.Id = int64(v)
		}
		offset += 8
	}

	if isPresent(1) {
		var _opt0 int32
		if offset+4 > len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		{
			v := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			_opt0 = int32(v)
		}
		offset += 4
		s.Score = &_opt0
	}
	return offset, nil
}
