package golang

import (
	"bytes"
	"fmt"
	"go/format"

	"github.com/snowmerak/antiserial/compiler/ast"
	"github.com/snowmerak/antiserial/compiler/codegen"
)

// goImports lists standard library imports required by generated code for a schema.
type goImports struct {
	fmt    bool
	io     bool
	math   bool
	unsafe bool
}

func collectGoImports(schemaAST ast.AST) goImports {
	imp := goImports{io: true}
	var walk func(ast.FieldType)
	walk = func(t ast.FieldType) {
		switch t.Kind {
		case ast.TypePrimitive:
			switch t.Name {
			case "string":
				imp.fmt = true
				imp.unsafe = true
			case "bytes":
				imp.fmt = true
				imp.unsafe = true
			case "float32", "float", "float64", "double":
				imp.math = true
			}
		case ast.TypeList, ast.TypeMap:
			imp.fmt = true
			if t.ElemType != nil {
				walk(*t.ElemType)
			}
			if t.KeyType != nil {
				walk(*t.KeyType)
			}
			if t.ValType != nil {
				walk(*t.ValType)
			}
		case ast.TypeStruct:
			if s, ok := schemaAST.FindStruct(t.Name); ok {
				for _, f := range s.Fields {
					walk(f.Type)
				}
			}
		}
	}
	for _, s := range schemaAST.Structs {
		for _, f := range s.Fields {
			walk(f.Type)
		}
	}
	return imp
}

func writeGoImportBlock(buf *bytes.Buffer, imp goImports) {
	buf.WriteString("import (\n")
	if imp.fmt {
		buf.WriteString("\t\"fmt\"\n")
	}
	if imp.io {
		buf.WriteString("\t\"io\"\n")
	}
	if imp.math {
		buf.WriteString("\t\"math\"\n")
	}
	if imp.unsafe {
		buf.WriteString("\t\"unsafe\"\n")
	}
	buf.WriteString(")\n")
}

// Generate translates the AST into high-performance, zero-allocation Go code.
func Generate(packageName string, schemaAST ast.AST) (string, error) {
	var buf bytes.Buffer
	imp := collectGoImports(schemaAST)

	// File Header
	buf.WriteString(fmt.Sprintf("// Code generated by asc. DO NOT EDIT.\npackage %s\n\n", packageName))
	writeGoImportBlock(&buf, imp)

	// Generate Struct definitions and Marshal/Unmarshal methods
	for _, s := range schemaAST.Structs {
		// Go Struct Definition
		buf.WriteString(fmt.Sprintf("\ntype %s struct {\n", s.Name))
		for _, field := range s.Fields {
			fieldName := capitalize(field.Name)
			buf.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldName, toGoType(field.Type), field.Name))
		}
		buf.WriteString("}\n")

		// Marshal Method
		buf.WriteString(fmt.Sprintf("\nfunc (s *%s) Marshal(buf []byte) ([]byte, error) {\n", s.Name))
		// Check presence variables
		for i, field := range s.Fields {
			fieldName := capitalize(field.Name)
			presenceExpr := genPresenceCheck("s."+fieldName, field.Type)
			buf.WriteString(fmt.Sprintf("\tf%dPresent := %s\n", i, presenceExpr))
		}

		numFields := len(s.Fields)
		numBitmapBytes := (numFields + 6) / 7
		if numBitmapBytes == 0 {
			numBitmapBytes = 1
		}

		// Initialize bitmap bytes
		for b := 0; b < numBitmapBytes; b++ {
			buf.WriteString(fmt.Sprintf("\tvar b%d byte\n", b))
			for bit := 0; bit < 7; bit++ {
				fieldIdx := b*7 + bit
				if fieldIdx < numFields {
					buf.WriteString(fmt.Sprintf("\tif f%dPresent {\n\t\tb%d |= 1 << %d\n\t}\n", fieldIdx, b, bit))
				}
			}
			// Set continuation bit if there are more bitmap bytes
			if b < numBitmapBytes-1 {
				buf.WriteString(fmt.Sprintf("\tb%d |= 1 << 7\n", b))
			}
			buf.WriteString(fmt.Sprintf("\tbuf = append(buf, b%d)\n", b))
		}

		// Serialize present fields
		for i, field := range s.Fields {
			fieldName := capitalize(field.Name)
			buf.WriteString(fmt.Sprintf("\tif f%dPresent {\n", i))
			serializeCode := genSerializeType(field.Type, "s."+fieldName, 0)
			buf.WriteString(indent(serializeCode, "\t\t"))
			buf.WriteString("\n\t}\n")
		}
		buf.WriteString("\treturn buf, nil\n}\n")

		// Unmarshal Method
		buf.WriteString(fmt.Sprintf("\nfunc (s *%s) Unmarshal(buf []byte) (int, error) {\n", s.Name))
		buf.WriteString(`	offset := 0
	bitmapStart := offset
	for {
		if offset >= len(buf) {
			return 0, io.ErrUnexpectedEOF
		}
		b := buf[offset]
		offset++
		if b&0x80 == 0 {
			break
		}
	}
	bitmapBytes := buf[bitmapStart:offset]

	isPresent := func(fieldIdx int) bool {
		byteIdx := fieldIdx / 7
		bitIdx := fieldIdx % 7
		if byteIdx >= len(bitmapBytes) {
			return false
		}
		return (bitmapBytes[byteIdx] & (1 << bitIdx)) != 0
	}
`)

		for i, field := range s.Fields {
			fieldName := capitalize(field.Name)
			buf.WriteString(fmt.Sprintf("\n\tif isPresent(%d) {\n", i))
			deserializeCode := genDeserializeType(field.Type, "s."+fieldName, 0)
			buf.WriteString(indent(deserializeCode, "\t\t"))
			buf.WriteString("\n\t}\n")
		}

		buf.WriteString("\treturn offset, nil\n}\n")
	}

	// Format code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, return unformatted code with error for debugging
		return buf.String(), fmt.Errorf("go fmt error: %w", err)
	}

	return string(formatted), nil
}

// capitalize capitalizes the first letter of a string.
func capitalize(s string) string {
	if len(s) == 0 {
		return ""
	}
	// Handle Snake Case mapping to Camel Case if desired, but a simple capitalization of first char is robust.
	runes := []rune(s)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] = runes[0] - 'a' + 'A'
	}
	return string(runes)
}

// toGoType converts an AST type to a Go type (pointers for optional fields).
func toGoType(t ast.FieldType) string {
	base := toGoTypeValue(t)
	if t.Optional {
		return "*" + base
	}
	return base
}

func toGoTypeValue(t ast.FieldType) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "bool"
		case "int32":
			return "int32"
		case "uint32":
			return "uint32"
		case "int64":
			return "int64"
		case "uint64":
			return "uint64"
		case "float32", "float":
			return "float32"
		case "float64", "double":
			return "float64"
		case "string":
			return "string"
		case "bytes":
			return "[]byte"
		default:
			return t.Name
		}
	case ast.TypeStruct:
		return t.Name
	case ast.TypeList:
		return "[]" + toGoTypeValue(*t.ElemType)
	case ast.TypeMap:
		return "map[" + toGoTypeValue(*t.KeyType) + "]" + toGoTypeValue(*t.ValType)
	default:
		return ""
	}
}

func derefExpr(expr string, t ast.FieldType) string {
	if t.Optional {
		return "*" + expr
	}
	return expr
}

// genPresenceCheck generates a boolean expression checking if a field is present on the wire.
func genPresenceCheck(expr string, t ast.FieldType) string {
	if t.Optional {
		return expr + " != nil"
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return expr
		case "int32", "uint32", "int64", "uint64", "float32", "float64", "float", "double":
			return expr + " != 0"
		case "string":
			return expr + ` != ""`
		case "bytes":
			return fmt.Sprintf("len(%s) > 0", expr)
		}
	case ast.TypeStruct:
		// Nested structs are always serialized to preserve their empty bitmaps
		return "true"
	case ast.TypeList, ast.TypeMap:
		return fmt.Sprintf("len(%s) > 0", expr)
	}
	return "false"
}

// genSerializeType recursively generates Go code for serializing a type.
func genSerializeType(t ast.FieldType, expr string, depth int) string {
	val := derefExpr(expr, t)
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf(`if %s {
	buf = append(buf, 1)
} else {
	buf = append(buf, 0)
}`, val)
		case "int32", "uint32":
			return fmt.Sprintf(`{
	v := uint32(%s)
	buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}`, val)
		case "int64", "uint64":
			return fmt.Sprintf(`{
	v := uint64(%s)
	buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}`, val)
		case "float32", "float":
			return fmt.Sprintf(`{
	v := math.Float32bits(%s)
	buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}`, val)
		case "float64", "double":
			return fmt.Sprintf(`{
	v := math.Float64bits(%s)
	buf = append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}`, val)
		case "string":
			return fmt.Sprintf(`{
	length := len(%s)
	if length > %d {
		return nil, fmt.Errorf("antiserial: string length %%d exceeds uint16 maximum %d", length)
	}
	buf = append(buf, byte(length), byte(length>>8))
	buf = append(buf, %s...)
}`, val, codegen.MaxUint16, codegen.MaxUint16, val)
		case "bytes":
			return fmt.Sprintf(`{
	length := len(%s)
	if length > 0xffffffff {
		return nil, fmt.Errorf("antiserial: bytes length %%d exceeds uint32 maximum", length)
	}
	buf = append(buf, byte(length), byte(length>>8), byte(length>>16), byte(length>>24))
	buf = append(buf, %s...)
}`, val, val)
		}
	case ast.TypeStruct:
		return fmt.Sprintf(`{
	var err error
	buf, err = %s.Marshal(buf)
	if err != nil {
		return nil, err
	}
}`, val)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemCode := genSerializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`{
	count := len(%s)
	if count > %d {
		return nil, fmt.Errorf("antiserial: list length %%d exceeds uint16 maximum %d", count)
	}
	buf = append(buf, byte(count), byte(count>>8))
	for _, %s := range %s {
%s
	}
}`, val, codegen.MaxUint16, codegen.MaxUint16, elemName, val, indent(elemCode, "\t\t"))
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyCode := genSerializeType(*t.KeyType, keyName, depth+1)
		valCode := genSerializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`{
	count := len(%s)
	if count > %d {
		return nil, fmt.Errorf("antiserial: map length %%d exceeds uint16 maximum %d", count)
	}
	buf = append(buf, byte(count), byte(count>>8))
	for %s, %s := range %s {
%s
%s
	}
}`, val, codegen.MaxUint16, codegen.MaxUint16, keyName, valName, val, indent(keyCode, "\t\t"), indent(valCode, "\t\t"))
	}
	return ""
}

// genDeserializeType recursively generates Go code for deserializing a type.
func genDeserializeType(t ast.FieldType, expr string, depth int) string {
	if t.Optional {
		return genDeserializeOptional(t, expr, depth)
	}
	return genDeserializeTypeValue(t, expr, depth)
}

func genDeserializeOptional(t ast.FieldType, expr string, depth int) string {
	if t.Kind == ast.TypeStruct {
		return fmt.Sprintf(`%s = &%s{}
{
	n, err := %s.Unmarshal(buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n
}`, expr, t.Name, expr)
	}
	tmp := fmt.Sprintf("_opt%d", depth)
	inner := t
	inner.Optional = false
	body := fmt.Sprintf("var %s %s\n%s", tmp, toGoTypeValue(inner), indent(genDeserializeTypeValue(inner, tmp, depth), "\t"))
	return body + fmt.Sprintf("\n\t%s = &%s", expr, tmp)
}

func genDeserializeTypeValue(t ast.FieldType, expr string, depth int) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf(`if offset >= len(buf) {
	return 0, io.ErrUnexpectedEOF
}
%s = buf[offset] != 0
offset++`, expr)
		case "int32", "uint32":
			cast := "int32"
			if t.Name == "uint32" {
				cast = "uint32"
			}
			return fmt.Sprintf(`if offset+4 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	v := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
	%s = %s(v)
}
offset += 4`, expr, cast)
		case "int64", "uint64":
			cast := "int64"
			if t.Name == "uint64" {
				cast = "uint64"
			}
			return fmt.Sprintf(`if offset+8 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
	%s = %s(v)
}
offset += 8`, expr, cast)
		case "float32", "float":
			return fmt.Sprintf(`if offset+4 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	v := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
	%s = math.Float32frombits(v)
}
offset += 4`, expr)
		case "float64", "double":
			return fmt.Sprintf(`if offset+8 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	v := uint64(buf[offset]) | uint64(buf[offset+1])<<8 | uint64(buf[offset+2])<<16 | uint64(buf[offset+3])<<24 | uint64(buf[offset+4])<<32 | uint64(buf[offset+5])<<40 | uint64(buf[offset+6])<<48 | uint64(buf[offset+7])<<56
	%s = math.Float64frombits(v)
}
offset += 8`, expr)
		case "string":
			return fmt.Sprintf(`if offset+2 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	length := uint16(buf[offset]) | uint16(buf[offset+1])<<8
	offset += 2
	if offset+int(length) > len(buf) {
		return 0, io.ErrUnexpectedEOF
	}
	if length > 0 {
		%s = unsafe.String(&buf[offset], length)
		offset += int(length)
	} else {
		%s = ""
	}
}`, expr, expr)
		case "bytes":
			return fmt.Sprintf(`if offset+4 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	length := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
	offset += 4
	if offset+int(length) > len(buf) {
		return 0, io.ErrUnexpectedEOF
	}
	if length > 0 {
		%s = unsafe.Slice(&buf[offset], length)
		offset += int(length)
	} else {
		%s = nil
	}
}`, expr, expr)
		}
	case ast.TypeStruct:
		return fmt.Sprintf(`{
	n, err := (&%s).Unmarshal(buf[offset:])
	if err != nil {
		return 0, err
	}
	offset += n
}`, expr)
	case ast.TypeList:
		elemName := fmt.Sprintf("elem%d", depth)
		elemTypeStr := toGoTypeValue(*t.ElemType)
		elemCode := genDeserializeType(*t.ElemType, elemName, depth+1)
		return fmt.Sprintf(`if offset+2 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	count := uint16(buf[offset]) | uint16(buf[offset+1])<<8
	offset += 2
	%s = make([]%s, count)
	for i := 0; i < int(count); i++ {
		var %s %s
%s
		%s[i] = %s
	}
}`, expr, elemTypeStr, elemName, elemTypeStr, indent(elemCode, "\t\t"), expr, elemName)
	case ast.TypeMap:
		keyName := fmt.Sprintf("k%d", depth)
		valName := fmt.Sprintf("v%d", depth)
		keyTypeStr := toGoType(*t.KeyType)
		valTypeStr := toGoType(*t.ValType)
		keyCode := genDeserializeType(*t.KeyType, keyName, depth+1)
		valCode := genDeserializeType(*t.ValType, valName, depth+1)
		return fmt.Sprintf(`if offset+2 > len(buf) {
	return 0, io.ErrUnexpectedEOF
}
{
	count := uint16(buf[offset]) | uint16(buf[offset+1])<<8
	offset += 2
	%s = make(map[%s]%s, count)
	for i := 0; i < int(count); i++ {
		var %s %s
%s
		var %s %s
%s
		%s[%s] = %s
	}
}`, expr, keyTypeStr, valTypeStr, keyName, keyTypeStr, indent(keyCode, "\t\t"), valName, valTypeStr, indent(valCode, "\t\t"), expr, keyName, valName)
	}
	return ""
}

// indent prefixes each line of s with the given prefix.
func indent(s, prefix string) string {
	var buf bytes.Buffer
	lines := bytes.Split([]byte(s), []byte("\n"))
	for i, line := range lines {
		if i > 0 {
			buf.WriteByte('\n')
		}
		if len(line) > 0 {
			buf.WriteString(prefix)
			buf.Write(line)
		}
	}
	return buf.String()
}
